apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: test-build-push-run-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: test-build-push
  serviceAccountName: pipeline
  resources:
    - name: source
      resourceRef:
        name: source
    - name: image
      resourceRef:
        name: image
