apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: buildah-task-run-
spec:
  serviceAccountName: pipeline
  taskRef:
    name: buildah
  inputs:
    resources:
      - name: source
        resourceRef:
          name: source
  outputs:
    resources:
      - name: image
        resourceRef:
          name: image
