apiVersion: v1
kind: Pod
metadata:
  name: website-pod
  namespace: web
spec:
  containers:
  - name: website-container
    image: nginx
    command: ['nginx']
    args: ['-g', 'daemon off;', '-q']
    ports:
    - containerPort: 80

