apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-app
    image: bitnami/nginx
    ports:
      - containerPort: 8080
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
    envFrom:
      - secretRef:
          name: mysecret
    volumeMounts:
      - name: config
        mountPath: "/etc/secrets"
  volumes:
    - name: config
      secret:
        secretName: mysecret-config