apiVersion: apps/v1
kind: Deployment
metadata:
  name: jedi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jedi
  template:
    metadata:
      labels:
        app: jedi
    spec:
      containers:
        - image: bitnami/nginx:1.16.1
          name: c
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoda-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yoda
  template:
    metadata:
      labels:
        app: yoda
    spec:
      containers:
        - image: bitnami/nginx:1.16.1
          name: c
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jedi-svc
spec:
  type: NodePort
  selector:
    app: jedi
  ports:
    - name: http
      port: 80
      targetPort: http
---
  apiVersion: v1
  kind: Service
  metadata:
    name: yoda-svc
  spec:
    type: ClusterIP
    selector:
      app: yoda
    ports:
      - name: http
        port: 80
        targetPort: http  
